name             'libpg-helper'
maintainer       'Chris Zeeb'
maintainer_email 'chris.zeeb@gmail.com'
license          'Apache 2.0'
description      'Installs postgres'
long_description ''
version          '1.0.6'

depends 'database', '~> 4.0'
depends 'gearman', '~> 1.0'
depends 'postgresql', '~> 3.4'