name             'mysql-helper'
maintainer       'Chris Zeeb'
maintainer_email 'chris.zeeb@gmail.com'
license          'Apache 2.0'
description      'Installs mysql'
long_description ''
version          '1.0.0'

depends 'database', '~> 4.0'
depends 'gearman', '~> 1.0'
depends 'mysql', '~> 6.1'
depends 'mysql2_chef_gem', '~> 1.0'
