name             'memcached-helper'
maintainer       'Chris Zeeb'
maintainer_email 'chris.zeeb@gmail.com'
license          'Apache 2.0'
description      'Installs memcached'
long_description ''
version          '1.0.0'

depends 'memcached', '~> 2.0'
depends 'gearman', '~> 1.0'
